[package]
name = "scuffle-http-examples"
version = "0.1.0"
edition = "2021"

[[example]]
name = "scuffle-http-axum"
path = "src/axum.rs"

[dev-dependencies]
axum = { version = "0.8.1", features = ["macros"] }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
rustls = "0.23.21"
rustls-pemfile = "2.2.0"
scuffle-http.workspace = true
scuffle-workspace-hack.workspace = true
