[package]
name = "scuffle-http"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/scufflecloud/scuffle"
authors = ["Scuffle <opensource@scuffle.cloud>"]
readme = "README.md"
documentation = "https://docs.rs/scuffle-http"
license = "MIT OR Apache-2.0"
description = "A high-performance HTTP server supporting HTTP/1.1, HTTP/2, and HTTP/3."
keywords = ["http", "server", "http1", "http2", "http3"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[dependencies]
tokio = { version = "1.43.0" }
tower = { version = "0.5.2", features = ["make"] }
thiserror = "2.0.11"
scuffle-context.workspace = true

# HTTP parsing
http = "1.2.0"
http-body = "1.0.1"
bytes = "1.9.0"

# Tracing
tracing = "0.1.41"

# HTTP/1.1, HTTP/2
# hyper = { version = "1.6.0", features = ["http1", "http2", "server", "tracing"] }
hyper = { version = "1.6.0", features = ["http1", "http2", "server"] }
hyper-util = { version = "0.1.10", features = ["server-auto", "tokio"] }

# QUIC + HTTP/3
quinn = { version = "0.11.6", features = ["aws-lc-rs"] }
h3-quinn = { version = "0.0.7", features = ["tracing"] }
h3 = { version = "0.0.6", features = ["tracing"] }

# TLS
tokio-rustls = "0.26.1"
rustls = "0.23.21"
futures = "0.3.31"

scuffle-workspace-hack.workspace = true

[dev-dependencies]
reqwest = { version = "0.12.12", default-features = false, features = ["rustls-tls"] }
rustls-pemfile = "2.2.0"
scuffle-future-ext.workspace = true
