name: Create Crate Release

on:
  workflow_dispatch:
    inputs:
      crate:
        required: true
        type: string

env:
  RUST_TOOLCHAIN: nightly

jobs:
  create-release:
    name: Create Release
    runs-on: ubicloud-standard-8
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          shared-key: create-release
          tools: just,release-plz
          cache-backend: ubicloud

      - name: Create release
        id: create
        run: |
          set -eo pipefail
          release=$(just create-release ${{ inputs.crate }})
          echo $release > /tmp/release.txt
          echo $release > $GITHUB_STEP_SUMMARY

      # Check if any files changed
      - name: Check if anything changed
        id: changed
        run: |
          result=$((git diff --exit-code > /dev/null && echo '0') || echo '1')
          echo "result=$result" >> $GITHUB_OUTPUT

      - name: Create github PR
        uses: peter-evans/create-pull-request@v7
        if: ${{ steps.changed.outputs.result == 1 }}
        with:
          title: Automated release of ${{ inputs.crate }}
          body-path: /tmp/release.txt
          branch: create-release/${{ inputs.crate }}
          commit-message: |
            Automated release of ${{ inputs.crate }}
            ${{ steps.create.outputs.release }}
